config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: "home#top"
  resources :pictures do
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  
  validates :picture, presence: true
  validates :caption, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :picture
  
  validates :comment_body, presence: true
  validates :comment_name, presence: true, length: {maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :pictures, dependent: :destroy
  attachment :profile_image
  attachment :show_image
  attachment :active_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :show, :index, :new, :create]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @pictures = Picture.page(params[:page]).reverse_order
    @user = User.find(id=2)
  end 
end 

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @picture = Picture.new
  end
  
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to pictures_path
    else
      render :new
    end
    
  end
  
  def index
    @pictures = Picture.all
  end
  
  def show
    @picture = Picture.find(params[:id])
    @post_comment = PostComment.new
  end
  
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end
  
  def edit
    @picture = Picture.find(params[:id])
  end
  
  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to picture_path(@picture.id)
    else
      render :edit
    end
  end
  
  private
  
  def picture_params
    params.require(:picture).permit(:picture, :image, :caption)
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    picture = Picture.find(params[:picture_id])
    comment = PostComment.new(post_comment_params)
    comment.picture_id = picture.id
    if comment.save
    flash[:success] = "投稿が完了しました！"
    redirect_to picture_path(picture) 
    else
      flash[:alert] = "投稿に失敗しました！"
      redirect_to picture_path(picture) 
    end
  end

  def destroy
    PostComment.find_by(id: params[:id], picture_id: params[:picture_id]).destroy
    redirect_to picture_path(params[:picture_id])
  end
  
  private
  def post_comment_params
    params.require(:post_comment).permit(:comment_body, :comment_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  private
  def user_params
    params.require(:user).permit(:like, :can, :profile_image, :show_image, :active_image, :show_title, :active_title, :show_body, :active_body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="main-visual">
    <div class="bgimg src1"></div>
    <div class="bgimg src2"></div>
    <div class="bgimg src3"></div>
</div>

<div class="main">
    <section class="about">
        <h2 class="about-heading">
            <span>
                PASSION
            </span>
        </h2>
        <div class="about-text">
            
            
            <h3 class="about-text-heading">
                <span>
                    安らぎ、北欧風のタッチ。
                </span>
            </h3>
            <p class="about-text-p">
                <span>
                    柔らかい雰囲気を醸し出しつつ、しっかりと「人」の良さを捉える。
                    <br>
                    北欧国に漂うひつじ雲のように自由に軽やかに。そして、懸命に・・・
                </span>
            </p>
            <p class="about-text-p">
                <span>
                    ”SJH HAV”の心が、描いたPictureに宿る。
                </span>
            </p>
            <p class="about-text-p">
                <span>
                    私は、見てくだっさた人が「笑顔」と「元気」をもらえるような
                    <br>そんな絵を創造したい。
                </span>
            </p>
            <p class="about-text-p">
                <span class="last-text">
                    世界中に届く日がいつか来るといいなぁ。
                </span>
            </p>
            
        </div>
    </section>
    <section class="pictures">
        <h2 class="pictures-heading">
            <span>
                PICTURES
            </span>
        </h2>
        <div class="pictures-list">
            <% @pictures.each do |picture| %>
            <article class="picture-article">
                <div class="picture-article-item">
                    <%= link_to picture_path(picture.id) do %>
                    <%= attachment_image_tag picture, :image, class: "list-image" %>
                    <% end %>
                    <div class="list-text">
                        <h6 class="created-day"><%= picture.created_at.strftime("%Y.%m.%d") %></h6>
                        <h4 class="list-text-body"><%= picture.picture %></h4>
                    </div>
                </div>
            </article>
            <% end %>
        </div>
        <div class="pictures-btn">
            <%= link_to "Picture一覧", pictures_path, class: "btn btn-outline-info" %>
        </div>
        <div class="about-text-profile">
            <h2 class="about-heading">
                <span>
                    ILLUSTRATOR
                </span>
            </h2>
            <div class="profile-image">
                <div class="nanami-image"><%= attachment_image_tag @user, :profile_image, class: "nanami-image-img" %></div>
            </div>
            <div class="about-text-profile-body">
                <div class="profile-name">
                    <h4 class="nanami-name">岡 本 七 海
                    <br><h6 class="nanami-name">O k a m o t o N a n a m i</h6>
                    </h4>
                <div class="profile-name-line"></div>
                </div>
                <div class="profile-day">
                    <h5>2000 8.18</h4>
                    <div class="profile-day-line"></div>
                </div>
                <div class="profile-place">
                    <h5>京都府出身</h4>
                    <div class="profile-place-line"></div>
                </div>
            </div>
            <div class="user-show">
                <%= link_to "ILLUSTRATOR詳細", "users/2", class: "btn btn-outline-success" %>
            </div>
        </div>
    </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NanamiBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/earlyaccess/sawarabigothic.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/earlyaccess/roundedmplus1c.css" rel="stylesheet" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>
    <header>
      <div class="header-logo">
        <%= link_to root_path, class: "link-none" do %>
        <h2 class="link-none">
          <%= image_tag "logo.png", class: "logo-image" %>
        </h2>
        <% end %>
      </div>
      <div id="nav-toggle">
        <div>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      
      <div id="gloval-nav">
        <nav>
          <ul>
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "HOMEへ戻る", root_path, class: "fas fa-home nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Picture一覧", pictures_path, class: "fas fa-palette nav-link" %>
            </li>
            <div class="nanami-only">
              <li class="nav-item">
                <h3 class="text">七海専用リンク</h3>
              </li>
              <li class="nav-item">
                <%= link_to "Picture投稿", new_picture_path, class: "fas fa-plus-circle nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Illustrator詳細", user_path(current_user.id), class: "fas fa-user nav-link" %>
              </li>
            </div>
            <% else %>
            <li class="nav-item">
              <%= link_to "HOMEへ戻る", root_path, class: "fas fa-home nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Picture一覧", pictures_path, class: "fas fa-palette nav-link" %>
            </li>
            <% end %>
          </ul>
        </nav>
      </div><!-- /#gloval-nav -->
    </header>
    <%= yield %>
    <footer>
      
      <div class="footer-text">
        <h6><%= link_to "Home", root_path, class: "footer-nav" %></h6>
        <h6><%= link_to "Pictures", pictures_path, class: "footer-nav" %></h6>
        <h6><%= link_to "運営Login", new_user_session_path, class: "footer-nav" %></h6>
      </div>
      <div class="footer-sns">
        <%= link_to "https://twitter.com/__nana_la__" do %>
          <i class="fab fa-twitter fa-2x"></i>
        <% end %>
        <%= link_to "https://www.instagram.com/sju_hav_/" do %>
          <i class="fab fa-instagram fa-2x"></i>
        <% end %>
      </div>
      <p class="copywrite">
        © 2020 Nanami Blog
      </p>
    </footer>
  </body>
</html>

 
              
           

app/views/pictures/edit.html.erb
<div class="container">
  <h1>イラスト画像編集フォーム</h1>
  <%= form_with model: @picture, local:true do |f| %>
    <h4>イラスト画像</h4>
    <%= f.attachment_field :image %>
    <h4>イラストタイトル</h4>
    <%= f.text_field :picture %>
    <h4>イラスト説明</h4>
    <%= f.text_area :caption %>
    <%= f.submit "保存" %>
  <% end %>
</div>

app/views/pictures/index.html.erb
<div class="main-visual">
    <div class="bgimg src1"></div>
    <div class="bgimg src2"></div>
    <div class="bgimg src3"></div>
</div>
<div class="main">
    <section class="pictures">
        <h2 class="pictures-heading">
            <span>
                PICTURES
            </span>
        </h2>
        <% @pictures.each do |picture| %>
        <div class="pictures-list">
            <article class="picture-article">
                <div class="picture-article-item">
                    <%= link_to picture_path(picture.id) do %>
                        <%= attachment_image_tag picture, :image, class: "list-image" %>
                    <% end %>
                    <div class="list-text">
                        <h6 class="created-day"><%= picture.created_at.strftime("%Y.%m.%d") %></h6>
                        <h4 class="list-text-body"><%= picture.picture %></h4>
                    </div>
                </div>
            </article>
        </div>
        <% end %>
    </section>
</div>

app/views/pictures/new.html.erb
<div class="container">
  <h1>イラスト画像投稿フォーム</h1>
  <%= form_with model: @picture, local:true do |f| %>
    <h4>イラスト画像</h4>
    <%= f.attachment_field :image %>
    <h4>イラストタイトル</h4>
    <%= f.text_field :picture %>
    <h4>イラスト説明</h4>
    <%= f.text_area :caption %>
    <%= f.submit "投稿" %>
  <% end %>
</div>

app/views/pictures/show.html.erb
<div class="illust">
  <%= attachment_image_tag @picture, :image, class: "illust-image-show" %>
  <div class="illust-text">
    <h5 class="illust-day"><%= @picture.created_at.strftime("%Y.%m.%d") %></h5>
    <div class="illust-title">
      <h3>『<%= @picture.picture %>』</h3>
    </div>
    <p class="illust-caption">
      <%= @picture.caption %>
    </p>
  </div>
  <% if @picture.user == current_user %>
    <div class="illust-edit">
      <%= link_to "削除", picture_path(@picture), method: :delete, class: "illust btn btn-danger" %>
      <%= link_to "編集", edit_picture_path(@picture), class: "btn btn-success" %>
    </div>
  <% end %>
  
  <div class="comment">
    <div class="comment-area">
      <h4>Comments</h4>
      <% @picture.post_comments.each do |post_comment| %>
      <div class="comment-text">
        <div class="comment-small">
          <p class="comment-day"><%= post_comment.created_at.strftime("%Y/%m/%d") %></p>
          <p class="comment-name"><i class="fas fa-user"></i><%= post_comment.comment_name %></p>
        </div>
        <p class="comment-body"><%= post_comment.comment_body %></p>
      </div>
      <% if user_signed_in? %>
        <div class="comment-delete">
          <%= link_to "削除", picture_post_comment_path(post_comment.picture, post_comment), method: :delete, class: "btn btn-outline-danger" %>
        </div>
      <% end %>
      <% end %>
    </div>
    <div class="notice-message">
    <label class="success-message"><%= flash[:success] %></label>
    <label class="alert-message"><%= flash[:alert]%></label>
    </div>
    <div class="comment-new">
      <%= form_with(model:[@picture, @post_comment], local: true) do |f| %>
      <div class="new-name">
        <label class="new-name-title">Name</label>
        <%= f.text_field :comment_name, class: "new-name-form" %>
      </div>
      <div class="new-body">
        <label class="new-body-title">comment</label>
        <%= f.text_area :comment_body, class: "new-body-form" %>
      </div>
        <%= f.submit "投稿", class: "btn" %>
      <% end %>
    </div>
  </div>
  
  <div class="illust-pictures-btn">
    <%= link_to "Picture一覧に戻る", pictures_path, class: "btn btn-outline-info" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1>プロフィール編集</h1>
  <%= form_with model:@user, local:true do |f| %>
  <div class="mylike">
    <h3>自己紹介</h3>
    <div class="profile-image-edit">
      <label for="inputImage" class="profile-image-title">ProfileImage</label>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "profile-image-form" %>
    </div>
    <div class="love-edit">
      <label for="inputlike" class="like-title">好きなもの</label>
      <%= f.text_area :like, class: "like-form" %>
      <label for="inputcan" class="can-title">得意なこと</label>
      <%= f.text_area :can, class: "can-form" %>
    </div>
  </div>
  <div class="myintroduce">
    <h3>Introduce</h3>
    <div class="introduce-edit">
      <h4>Introduce1</h4>
      <div class="introduce-image-edit">
        <label for="inputImage" class="introduce-image-title">Introduce画像1</label>
        <%= f.attachment_field :show_image, placeholder: "Introduce画像1", class: "introduce-image-form" %>
      </div>
      <div class="introduce-text">
        <label for="inputintroduce_title1" class="introduce-text-title">Introduceタイトル1</label>
        <%= f.text_field :show_title, class: "introduce-title-form" %>
        
        <label for="inputintroduce_body1" class="introduce-text-body">Introduceテキスト1</label>
        <%= f.text_area :show_body, class: "introduce-body-form" %>
      </div>
    </div>
    <div class="introduce-edit">
      <h4>Introduce2</h4>
      <div class="introduce-image-edit">
        <label for="inputImage" class="introduce-image-title">Introduce画像2</label>
        <%= f.attachment_field :active_image, placeholder: "Introduce画像2", class: "introduce-image-form" %>
      </div>
      <div class="introduce-text">
      <label for="inputintroduce_title2" class="introduce-text-title">Introduceタイトル2</label>
      <%= f.text_field :active_title, class: "introduce-title-form" %>
      <label for="inputintroduce_body2" class="introduce-text-body">Introduceテキスト2</label>
      <%= f.text_area :active_body, class: "introduce-body-form" %>
      </div>
    </div>
  </div>
    <%= f.submit "変更を保存", class: "btn btn-info" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="main-visual">
    <div class="showimg user1"></div>
    <div class="showimg user2"></div>
    <div class="showimg user3"></div>
</div>

<div class="show-main">
    <section class="show-about">
        <div class="show-about-text">
            <div class="show-about-text-profile">
                <div class="show-about-text-profile-body">
                    <div class="show-profile-name">
                        <h4 class="show-nanami-name">岡 本 七 海
                        <br><h6 class="show-nanami-name">O k a m o t o N a n a m i</h6>
                        </h4>
                    </div>
                    <div class="show-profile-day">
                        <h5>2000 8.18</h5>
                    </div>
                    <div class="show-profile-place">
                        <h5>京都府出身</h5>
                    </div>
                    <% @users.each do |user| %>
                    <div class="show-profile-like">
                        <h5><%= user.like %></h5>
                    </div>
                    <div class="show-profile-can">
                        <h5><%= user.can %></h5>
                    </div>
                </div>
            </div>
            <div class="introduce">
            <h1 class="introduce-heading">
            <span>
                Introduce
            </span>
            </h1>
            </div>
           <div class="user-show-picture-image">
                <div class="show-picture-image"><%= attachment_image_tag user, :show_image, class: "show-picture-image" %></div>
            </div>
            <h3 class="show-about-text-heading"><%= user.show_title %></h3>
            <p class="show-about-text-p">
                <span class="show-about-text-p">
                    <%= user.show_body %>
               </span>
            </p>
            <div class="pictures-btn-center">
            <div class="show-pictures-btn">
            <%= link_to "Picture一覧", pictures_path, class: "btn btn-outline-info" %>
            </div>
            </div>
            
            <div class="user-show-picture-image">
                <div class="show-active-image"><%= attachment_image_tag user, :active_image, class: "active-picture-image" %></div>
            </div>
            <h3 class="show-about-text-heading"><%= user.active_title %></h3>
            <p class="show-about-text-p">
                <span class="show-about-text-p">
                    <%= user.active_body %>
               </span>
            </p>
        </div>
    </section>
</div>
<% end %>
<% if user_signed_in? %>
    <%= link_to "User編集", edit_user_path(@user), class: "fas fa-user-edit nav-link" %>
<% end %>

app/views/users/show.html.erb
<div class="show-profile-image">
    <%= attachment_image_tag @user, :profile_image, class: "profile-image-img" %>
</div>

<div class="show-main">
    <section class="show-about">
        <div class="show-about-text">
            <div class="show-about-text-profile">
                <div class="show-about-text-profile-body">
                    <div class="show-profile-name">
                        <h4 class="show-nanami-name">岡 本 七 海
                        <br><h6 class="show-nanami-name">O k a m o t o N a n a m i</h6>
                        </h4>
                    </div>
                    <div class="show-profile-day">
                        <h5>2000 8.18</h5>
                    </div>
                    <div class="show-profile-place">
                        <h5>京都府出身</h5>
                    </div>
                    <div class="show-profile-like">
                        <h5><%= @user.like %></h5>
                    </div>
                    <div class="show-profile-can">
                        <h5><%= @user.can %></h5>
                    </div>
                </div>
            </div>
            <div class="introduce">
            <h1 class="introduce-heading">
            <span>
                Introduce
            </span>
            </h1>
            </div>
           <div class="user-show-picture-image">
                <div class="show-picture-image"><%= attachment_image_tag @user, :show_image, class: "show-picture-image-img" %></div>
            </div>
            <h3 class="show-about-text-heading"><%= @user.show_title %></h3>
            <p class="show-about-text-p">
                <span class="show-about-text-p">
                    <%= @user.show_body %>
               </span>
            </p>
            <div class="pictures-btn-center">
            <div class="show-pictures-btn">
            <%= link_to "Picture一覧", pictures_path, class: "btn btn-outline-info" %>
            </div>
            </div>
            
            <div class="user-show-picture-image">
                <div class="show-picture-image"><%= attachment_image_tag @user, :active_image, class: "show-picture-image-img" %></div>
            </div>
            <h3 class="show-about-text-heading"><%= @user.active_title %></h3>
            <p class="show-about-text-p">
                <span class="show-about-text-p">
                    <%= @user.active_body %>
               </span>
            </p>
        </div>
    </section>
</div>
<div class="user-edit-btn">
    <% if user_signed_in? %>
        <%= link_to "User編集", edit_user_path(@user), class: "fas fa-user-edit nav-link" %>
    <% end %>
</div>